version: "3.4"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    container_name: mongodb
    env_file: ./env_vars/.db
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb

  redis:
    image: redis:latest
    restart: always
    container_name: cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
  redis-data: